services:
  backend:
    build: ./backend
    ports: 
    - "8000:8000"
    volumes: 
      - /home/azureuser/Hackathon/backend/watched_folder:/app/watched_folder  # Lien entre la VM et le conteneur
      - /home/azureuser/Hackathon/backend/network_traffic.db:/app/network_traffic.db
    restart: always

  frontend:
    build: ./frontend
    ports:
    - "8051:8051"
    volumes:
    - ./frontend:/app
    depends_on:
    - backend
    restart: always