name: Deploy to Azure

on:
  push:
    branches:
      - main  # Déclenche la CI/CD à chaque push sur "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Récupère le code depuis GitHub

      - name: Login to Azure Container Registry (ACR)
        with:
            username: ${{ secrets.AZURE_CLIENT_ID }}
            password: ${{ secrets.AZURE_CLIENT_SECRET }} \
            tenant: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build & Push Backend
        run: |
          docker build -t monregistry.azurecr.io/backend:latest -f backend/Dockerfile .
          docker push monregistry.azurecr.io/backend:latest

      - name: Deploy Backend
        run: |
          az container create --resource-group mon-groupe \
            --name backend-api \
            --image monregistry.azurecr.io/backend:latest \
            --dns-name-label backend-app \
            --ports 8051


          