name: Deploy to Azure

on:
  push:
    branches:
      - main  # Déclenche la CI/CD à chaque push sur "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Récupère le code depuis GitHub

      - name: Login to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | az login --service-principal \
            --username ${{ ce6d9367-63ca-4053-83f7-14fcd52aa704 }} \
            --password ${{ ZBf8Q~E1pbft5FpCtn2JGHBalbX.7ZzN4VTyHaJd }} \
            --tenant ${{38e72bba-3c22-4382-9323-ac1612931297 }}

      - name: Build & Push Backend
        run: |
          docker build -t monregistry.azurecr.io/backend:latest -f backend/Dockerfile .
          docker push monregistry.azurecr.io/backend:latest

      - name: Deploy Backend
        run: |
          az container create --resource-group mon-groupe \
            --name backend-api \
            --image monregistry.azurecr.io/backend:latest \
            --dns-name-label backend-app \
            --ports 8051
          